import { AdminPreferences, UserPreferences } from './types/eureka'

export const DEFAULT_PREFERENCES: UserPreferences = {
  group_by_set: true,
  show_by_color: false,
  eureka_set_filter: null,
  eureka_category: null,
  eureka_obtained_filter: null,
  eureka_color: null,
  eureka_rarity: null,
  eureka_style: null,
  eureka_label: null,
  eureka_trial: null,
  theme: 'system',
  color_theme: 'default',
  text_scale: 'default',
  outfit_set_filter: null,
  outfit_category_filter: null,
  outfit_evolution_filter: null,
  outfit_rarity_filter: null,
  outfit_obtained_filter: null,
  outfit_style_filter: null,
  outfit_label_filter: null,
  outfit_season_filter: null,
  outfit_season_category_filter: null,
  outfit_group_by_set: true,
  outfit_hide_evolutions: false,
  outfit_hide_glowups: false,
  outfit_image_mode: 'image',
  outfit_density: 'standard',
  sort_order: 'new',
  outfit_sort_axis: 'date',
  momo_rarity_filter: null,
  momo_season_filter: null,
  momo_season_category_filter: null,
  momo_obtained_filter: null,
  momo_location_filter: null,
  makeup_sort_axis: 'date',
  makeup_density: 'standard',
  makeup_image_mode: 'image',
  season_hide_evolutions: true,
  season_hide_glowups: true,
  season_hide_pieces: false,
  season_hide_makeup: false,
  season_hide_base_sets: false,
  season_density: 'standard',
  season_obtained_filter: null,
  season_rarity_filter: null,
  season_style_filter: null,
}

export const DEFAULT_ADMIN_PREFERENCES: AdminPreferences = {
  admin_view: 'list',
}
