import { ColorTheme } from './types/eureka'

/**
 * An M3 tonal color role: the accent itself, the content drawn on top of it,
 * and the low-emphasis container pair. Names mirror the M3 tokens with the
 * role prefix dropped — `primary.on` is `on-primary`, `primary.onContainer`
 * is `on-primary-container`.
 */
export interface M3ColorRole {
  main: string
  on: string
  container: string
  onContainer: string
}

/**
 * The M3 surface roles. `main` is `surface`; `dim`/`bright` are its two
 * fixed extremes; `containerLowest` → `containerHighest` is the five-step
 * container ladder that replaced elevation overlays in M3. `on`/`onVariant`
 * are the content tones, `variant` the muted fill, and `inverse`/`inverseOn`
 * the reversed pair used by snackbars and tooltips.
 */
export interface M3SurfaceRoles {
  main: string
  dim: string
  bright: string
  containerLowest: string
  containerLow: string
  container: string
  containerHigh: string
  containerHighest: string
  on: string
  onVariant: string
  variant: string
  inverse: string
  inverseOn: string
}

/**
 * One complete M3 scheme. Everything MUI needs is derived from these tokens in
 * `buildColorSchemes` — `background` and `text` come from the surface roles and
 * `divider` from `outlineVariant`, so a preset never states the same color twice.
 */
export interface M3ColorScheme {
  primary: M3ColorRole
  secondary: M3ColorRole
  tertiary: M3ColorRole
  error: M3ColorRole
  /** Not an M3 role. Kept because the app uses MUI's `color="success"`. */
  success: M3ColorRole
  surface: M3SurfaceRoles
  outline: string
  outlineVariant: string
  inversePrimary: string
}

export interface ColorThemePreset {
  label: string
  description: string
  light: M3ColorScheme
  dark: M3ColorScheme
}

// Tones were generated by holding each key color's hue and chroma and moving
// L* to the M3 tone (tone N == L* N), clipping chroma to the sRGB gamut. The
// `moonlight` output reproduces the M3 baseline scheme, which is the check that
// the other three are in the same system.
export const COLOR_THEME_PRESETS: Record<ColorTheme, ColorThemePreset> = {
  default: {
    label: 'Terracotta',
    description: 'Warm earthy tones',
    light: {
      primary: {
        main: '#8F4C33',
        on: '#FFFFFF',
        container: '#FFDBCE',
        onContainer: '#321200',
      },
      secondary: {
        main: '#77574C',
        on: '#FFFFFF',
        container: '#FFDBCE',
        onContainer: '#2E1509',
      },
      tertiary: {
        main: '#3D6736',
        on: '#FFFFFF',
        container: '#C1EFB5',
        onContainer: '#0A2000',
      },
      error: {
        main: '#B3261E',
        on: '#FFFFFF',
        container: '#F9DEDC',
        onContainer: '#410E0B',
      },
      success: {
        main: '#695E2F',
        on: '#FFFFFF',
        container: '#F2E2AC',
        onContainer: '#211B00',
      },
      surface: {
        main: '#FFF8F6',
        dim: '#E8D6D1',
        bright: '#FFF8F6',
        containerLowest: '#FFFFFF',
        containerLow: '#FFF1EC',
        container: '#FCEAE4',
        containerHigh: '#F7E4DF',
        containerHighest: '#F1DFD9',
        on: '#211A18',
        onVariant: '#53433E',
        variant: '#F2DED8',
        inverse: '#362F2C',
        inverseOn: '#F9EFEB',
      },
      outline: '#84736D',
      outlineVariant: '#D5C3BC',
      inversePrimary: '#FFB599',
    },
    dark: {
      primary: {
        main: '#FFB59A',
        on: '#581D06',
        container: '#73341D',
        onContainer: '#FFDBCE',
      },
      secondary: {
        main: '#E7BEAF',
        on: '#452920',
        container: '#5E4035',
        onContainer: '#FFDBCE',
      },
      tertiary: {
        main: '#A2CF95',
        on: '#0D390B',
        container: '#265021',
        onContainer: '#C1EFB5',
      },
      error: {
        main: '#F2B8B5',
        on: '#601410',
        container: '#8C1D18',
        onContainer: '#F9DEDC',
      },
      success: {
        main: '#D5C692',
        on: '#383000',
        container: '#504719',
        onContainer: '#F2E2AC',
      },
      surface: {
        main: '#1A110E',
        dim: '#1A110E',
        bright: '#423733',
        containerLowest: '#140C09',
        containerLow: '#231A16',
        container: '#271E1A',
        containerHigh: '#322824',
        containerHighest: '#3D322F',
        on: '#EAE0DD',
        onVariant: '#D5C3BC',
        variant: '#53433E',
        inverse: '#EAE0DD',
        inverseOn: '#362F2C',
      },
      outline: '#9F8D87',
      outlineVariant: '#53433E',
      inversePrimary: '#8F4C33',
    },
  },
  moonlight: {
    label: 'Moonlight',
    description: 'Soft purples and lavender',
    light: {
      primary: {
        main: '#6750A4',
        on: '#FFFFFF',
        container: '#E9DDFF',
        onContainer: '#150D56',
      },
      secondary: {
        main: '#625B71',
        on: '#FFFFFF',
        container: '#E7DFF8',
        onContainer: '#1E192B',
      },
      tertiary: {
        main: '#7D5260',
        on: '#FFFFFF',
        container: '#FFD9E4',
        onContainer: '#330F1D',
      },
      error: {
        main: '#B3261E',
        on: '#FFFFFF',
        container: '#F9DEDC',
        onContainer: '#410E0B',
      },
      success: {
        main: '#695E2F',
        on: '#FFFFFF',
        container: '#F2E2AC',
        onContainer: '#211B00',
      },
      surface: {
        main: '#FFFBFE',
        dim: '#DED8E1',
        bright: '#FFFBFE',
        containerLowest: '#FFFFFF',
        containerLow: '#F7F2FA',
        container: '#F3EDF7',
        containerHigh: '#ECE6F0',
        containerHighest: '#E6E0E9',
        on: '#1D1B20',
        onVariant: '#494551',
        variant: '#E6E0EF',
        inverse: '#322F35',
        inverseOn: '#F2EFF7',
      },
      outline: '#7A7582',
      outlineVariant: '#C9C4D3',
      inversePrimary: '#D2BBFF',
    },
    dark: {
      primary: {
        main: '#D0BCFF',
        on: '#32226F',
        container: '#4C3889',
        onContainer: '#E9DDFF',
      },
      secondary: {
        main: '#CCC2DC',
        on: '#332D41',
        container: '#4A4358',
        onContainer: '#E7DFF8',
      },
      tertiary: {
        main: '#EFB8C8',
        on: '#4B2432',
        container: '#633B48',
        onContainer: '#FFD9E4',
      },
      error: {
        main: '#F2B8B5',
        on: '#601410',
        container: '#8C1D18',
        onContainer: '#F9DEDC',
      },
      success: {
        main: '#D5C692',
        on: '#383000',
        container: '#504719',
        onContainer: '#F2E2AC',
      },
      surface: {
        main: '#141218',
        dim: '#141218',
        bright: '#3B383E',
        containerLowest: '#0F0D13',
        containerLow: '#1D1B20',
        container: '#211F26',
        containerHigh: '#2B2930',
        containerHighest: '#36343B',
        on: '#E4E1E9',
        onVariant: '#C9C4D3',
        variant: '#494551',
        inverse: '#E4E1E9',
        inverseOn: '#322F35',
      },
      outline: '#938E9C',
      outlineVariant: '#494551',
      inversePrimary: '#6750A4',
    },
  },
  blossom: {
    label: 'Cherry Blossom',
    description: 'Deep rose and soft pink',
    light: {
      primary: {
        main: '#9C4063',
        on: '#FFFFFF',
        container: '#FFD9E4',
        onContainer: '#3E001E',
      },
      secondary: {
        main: '#775860',
        on: '#FFFFFF',
        container: '#FED9E2',
        onContainer: '#2D141B',
      },
      tertiary: {
        main: '#7E5700',
        on: '#FFFFFF',
        container: '#FFDDB0',
        onContainer: '#261900',
      },
      error: {
        main: '#B3261E',
        on: '#FFFFFF',
        container: '#F9DEDC',
        onContainer: '#410E0B',
      },
      success: {
        main: '#695E2F',
        on: '#FFFFFF',
        container: '#F2E2AC',
        onContainer: '#211B00',
      },
      surface: {
        main: '#FFF8F8',
        dim: '#EDD4D8',
        bright: '#FFF8F8',
        containerLowest: '#FFFFFF',
        containerLow: '#FFF0F2',
        container: '#FCE8EC',
        containerHigh: '#F7E2E6',
        containerHighest: '#F1DCE1',
        on: '#211A1C',
        onVariant: '#534247',
        variant: '#F2DDE3',
        inverse: '#362E31',
        inverseOn: '#F9EEF1',
      },
      outline: '#857278',
      outlineVariant: '#D5C1C7',
      inversePrimary: '#FFB0C9',
    },
    dark: {
      primary: {
        main: '#FFB1C8',
        on: '#630433',
        container: '#7E244A',
        onContainer: '#FFD9E4',
      },
      secondary: {
        main: '#E5BDBE',
        on: '#442830',
        container: '#5C3F46',
        onContainer: '#FED9E2',
      },
      tertiary: {
        main: '#F5BC3E',
        on: '#422C00',
        container: '#5F4100',
        onContainer: '#FFDDB0',
      },
      error: {
        main: '#F2B8B5',
        on: '#601410',
        container: '#8C1D18',
        onContainer: '#F9DEDC',
      },
      success: {
        main: '#D5C692',
        on: '#383000',
        container: '#504719',
        onContainer: '#F2E2AC',
      },
      surface: {
        main: '#1A1012',
        dim: '#1A1012',
        bright: '#433438',
        containerLowest: '#130B0D',
        containerLow: '#22191B',
        container: '#271D1F',
        containerHigh: '#32282A',
        containerHighest: '#3E3235',
        on: '#EAE0E3',
        onVariant: '#D5C1C7',
        variant: '#534247',
        inverse: '#EAE0E3',
        inverseOn: '#362E31',
      },
      outline: '#9F8C91',
      outlineVariant: '#534247',
      inversePrimary: '#9A3E61',
    },
  },
  forest: {
    label: 'Forest',
    description: 'Lush greens and earth',
    light: {
      primary: {
        main: '#3A6A2F',
        on: '#FFFFFF',
        container: '#BDF0AC',
        onContainer: '#0C2000',
      },
      secondary: {
        main: '#52634F',
        on: '#FFFFFF',
        container: '#D4E8D0',
        onContainer: '#111F0D',
      },
      tertiary: {
        main: '#38656A',
        on: '#FFFFFF',
        container: '#BBEBF0',
        onContainer: '#002023',
      },
      error: {
        main: '#B3261E',
        on: '#FFFFFF',
        container: '#F9DEDC',
        onContainer: '#410E0B',
      },
      success: {
        main: '#695E2F',
        on: '#FFFFFF',
        container: '#F2E2AC',
        onContainer: '#211B00',
      },
      surface: {
        main: '#F6FBF1',
        dim: '#D6DBCF',
        bright: '#F6FBF1',
        containerLowest: '#FFFFFF',
        containerLow: '#EFF5EA',
        container: '#E8F2E3',
        containerHigh: '#E3ECDE',
        containerHighest: '#DDE7D8',
        on: '#191D18',
        onVariant: '#41493E',
        variant: '#DBE5D8',
        inverse: '#2E312C',
        inverseOn: '#EDF2EB',
      },
      outline: '#717A6D',
      outlineVariant: '#C0C9BC',
      inversePrimary: '#A1D491',
    },
    dark: {
      primary: {
        main: '#9CD489',
        on: '#063900',
        container: '#205118',
        onContainer: '#BDF0AC',
      },
      secondary: {
        main: '#B0CBA6',
        on: '#253422',
        container: '#3B4B38',
        onContainer: '#D4E8D0',
      },
      tertiary: {
        main: '#80D0D9',
        on: '#01363B',
        container: '#1F4D52',
        onContainer: '#BBEBF0',
      },
      error: {
        main: '#F2B8B5',
        on: '#601410',
        container: '#8C1D18',
        onContainer: '#F9DEDC',
      },
      success: {
        main: '#D5C692',
        on: '#383000',
        container: '#504719',
        onContainer: '#F2E2AC',
      },
      surface: {
        main: '#0E1610',
        dim: '#0E1610',
        bright: '#2F3B2C',
        containerLowest: '#091210',
        containerLow: '#161E13',
        container: '#1A2217',
        containerHigh: '#252D21',
        containerHighest: '#30382C',
        on: '#DFE4DD',
        onVariant: '#C0C9BC',
        variant: '#41493E',
        inverse: '#DFE4DD',
        inverseOn: '#2E312C',
      },
      outline: '#8A9387',
      outlineVariant: '#41493E',
      inversePrimary: '#39692E',
    },
  },
}

/** MUI wants `contrastText`; M3 calls the same token `on-<role>`. */
function paletteColor(role: M3ColorRole) {
  return {
    main: role.main,
    contrastText: role.on,
    on: role.on,
    container: role.container,
    onContainer: role.onContainer,
  }
}

function buildPalette(scheme: M3ColorScheme) {
  return {
    primary: paletteColor(scheme.primary),
    secondary: paletteColor(scheme.secondary),
    tertiary: paletteColor(scheme.tertiary),
    error: paletteColor(scheme.error),
    success: paletteColor(scheme.success),
    surface: scheme.surface,
    outline: scheme.outline,
    outlineVariant: scheme.outlineVariant,
    inversePrimary: scheme.inversePrimary,
    // M3 folded `background` into `surface`; MUI still reads both, so they
    // point at the same token rather than drifting apart.
    background: { default: scheme.surface.main, paper: scheme.surface.main },
    text: { primary: scheme.surface.on, secondary: scheme.surface.onVariant },
    divider: scheme.outlineVariant,
  }
}

export function buildColorSchemes(preset: ColorThemePreset) {
  return {
    light: { palette: buildPalette(preset.light) },
    dark: { palette: buildPalette(preset.dark) },
  }
}
