-- 20260802120000_add_makeup_tables.sql
-- Makeup domain: sets (base + evolutions in one table, like outfit_sets),
-- variants (nullable set for standalone pieces), categories, and per-user
-- collection tracking.

begin;

-- 1. Category lookup. IDs are fixed in game order.
create table if not exists public.makeup_categories (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  image_url text,
  created_at timestamptz default now()
);

insert into public.makeup_categories (id, slug, title, image_url) values
  (1, 'base-makeup',    'Base Makeup',    '/icons/categories/base-makeup.png'),
  (2, 'eyebrows',       'Eyebrows',       '/icons/categories/eyebrows.png'),
  (3, 'eyelashes',      'Eyelashes',      '/icons/categories/eyelashes.png'),
  (4, 'contact-lenses', 'Contact Lenses', '/icons/categories/contact-lenses.png'),
  (5, 'lips',           'Lips',           '/icons/categories/lips.png')
on conflict (slug) do nothing;

-- Identity column was seeded explicitly; move the sequence past the seeds.
select setval(
  pg_get_serial_sequence('public.makeup_categories', 'id'),
  (select max(id) from public.makeup_categories)
);

-- 2. Sets. One row per makeup *state*: base = base_set IS NULL / order 1,
--    evolution = base_set IS NOT NULL / order >= 2. Title is intentionally NOT
--    unique (evolution subtitles repeat across sets); identity is on slug.
create table if not exists public.makeup_sets (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  rarity int not null,
  style text references public.styles(title) on update cascade,
  label text references public.labels(title) on update cascade,
  seasons text references public.seasons(title) on update cascade,
  season_category text references public.season_categories(title) on update cascade,
  outfit_set text references public.outfit_sets(slug) on update cascade on delete set null,
  "order" int not null default 1,
  base_set text references public.makeup_sets(slug) on update cascade on delete cascade,
  image_url text,
  alt_image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists makeup_sets_base_set_idx on public.makeup_sets (base_set);
create index if not exists makeup_sets_outfit_set_idx on public.makeup_sets (outfit_set);

-- 3. Variants. makeup_set is NULLABLE: a standalone piece belongs to no set and
--    carries its own rarity/style/label/title/description.
create table if not exists public.makeup_variants (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  makeup_set text references public.makeup_sets(slug) on update cascade on delete cascade,
  makeup_category text references public.makeup_categories(slug) on update cascade,
  title text,
  description text,
  rarity int,
  style text references public.styles(title) on update cascade,
  label text references public.labels(title) on update cascade,
  "default" boolean not null default false,
  image_url text,
  alt_image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists makeup_variants_makeup_set_idx on public.makeup_variants (makeup_set);

-- 4. Per-user collection.
create table if not exists public.obtained_makeup (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  makeup_set text not null,
  makeup_category text not null,
  makeup_variant text not null,
  created_at timestamptz not null default now(),
  constraint obtained_makeup_unique unique (user_id, makeup_set, makeup_category)
);

create index if not exists obtained_makeup_user_id_idx on public.obtained_makeup (user_id);

-- 5. updated_at triggers.
create trigger trg_makeup_sets_updated_at
  before update on public.makeup_sets
  for each row execute function public.set_updated_at();

create trigger trg_makeup_variants_updated_at
  before update on public.makeup_variants
  for each row execute function public.set_updated_at();

-- 6. Base-variant default flag, mirroring enforce_base_variant_default.
--    COALESCE matters: a standalone piece has makeup_set IS NULL, so the
--    subquery returns NULL and the flag must fall back to false rather than
--    NULL (the column is NOT NULL). Same fix as 20260630072105 for outfits.
create or replace function public.enforce_base_makeup_variant_default()
returns trigger
language plpgsql
as $$
begin
  new."default" := coalesce(
    (select s."order" = 1 from public.makeup_sets s where s.slug = new.makeup_set),
    false
  );
  return new;
end;
$$;

create trigger trg_enforce_base_makeup_variant_default
  before insert or update of makeup_set on public.makeup_variants
  for each row execute function public.enforce_base_makeup_variant_default();

-- 7. RLS: public read, admin write on content; owner-only on collection.
alter table public.makeup_categories enable row level security;
alter table public.makeup_sets       enable row level security;
alter table public.makeup_variants   enable row level security;
alter table public.obtained_makeup   enable row level security;

create policy makeup_categories_read on public.makeup_categories
  for select using (true);
create policy makeup_categories_admin_write on public.makeup_categories
  for all using ((select public.is_admin())) with check ((select public.is_admin()));

create policy makeup_sets_read on public.makeup_sets
  for select using (true);
create policy makeup_sets_admin_write on public.makeup_sets
  for all using ((select public.is_admin())) with check ((select public.is_admin()));

create policy makeup_variants_read on public.makeup_variants
  for select using (true);
create policy makeup_variants_admin_write on public.makeup_variants
  for all using ((select public.is_admin())) with check ((select public.is_admin()));

create policy obtained_makeup_public_select on public.obtained_makeup
  for select using (true);
create policy obtained_makeup_owner_insert on public.obtained_makeup
  for insert with check ((select auth.uid()) = user_id);
create policy obtained_makeup_owner_update on public.obtained_makeup
  for update using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy obtained_makeup_owner_delete on public.obtained_makeup
  for delete using ((select auth.uid()) = user_id);

-- 8. Toggle RPC, mirroring toggle_obtained_outfit (keys on variant alone).
create or replace function public.toggle_obtained_makeup(
  p_makeup_set text,
  p_makeup_category text,
  p_makeup_variant text
)
returns void
language plpgsql
security definer
set search_path to ''
as $$
begin
  delete from public.obtained_makeup
  where user_id       = (select auth.uid())
    and makeup_variant = p_makeup_variant;
  if not found then
    insert into public.obtained_makeup (user_id, makeup_set, makeup_category, makeup_variant)
    values ((select auth.uid()), p_makeup_set, p_makeup_category, p_makeup_variant);
  end if;
end;
$$;

commit;
