-- 20260803120000_add_momo_cloaks_table.sql
-- Momo's Cloaks domain: a single content table, mirroring the shape of
-- makeup_sets / outfit_sets. Lookup FKs point at `slug` (not `title`), matching
-- the convention set by 20260312000001_migrate_fks_to_slug.sql and the makeup
-- repoint in 20260802130000 — app code writes slugs into these columns.

begin;

create table if not exists public.momo_cloaks (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  title text not null,
  description text,
  rarity int,
  style text references public.styles(slug) on update cascade,
  label text references public.labels(slug) on update cascade,
  seasons text references public.seasons(slug) on update cascade,
  season_category text references public.season_categories(slug) on update cascade,
  image_url text,
  alt_image_url text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists momo_cloaks_seasons_idx on public.momo_cloaks (seasons);
create index if not exists momo_cloaks_season_category_idx on public.momo_cloaks (season_category);

create trigger trg_momo_cloaks_updated_at
  before update on public.momo_cloaks
  for each row execute function public.set_updated_at();

-- RLS: public read, admin write — same as makeup_sets / outfit_sets.
alter table public.momo_cloaks enable row level security;

create policy momo_cloaks_read on public.momo_cloaks
  for select using (true);
create policy momo_cloaks_admin_write on public.momo_cloaks
  for all using ((select public.is_admin())) with check ((select public.is_admin()));

commit;
