-- 20260803130000_add_obtained_momo_cloaks.sql
-- Per-user collection tracking for Momo's Cloaks.
--
-- Unlike makeup and outfits, momo_cloaks is a flat table: no variants, no
-- categories. So the collection row keys on the cloak slug alone rather than
-- the (set, category, variant) triple those domains use — a cloak is simply
-- obtained or not. The FK is a real constraint here (obtained_makeup keys on
-- bare text with no FK); momo_cloaks.slug is UNIQUE, so it can carry one, and
-- ON DELETE CASCADE drops collection rows when a cloak is removed.

begin;

create table if not exists public.obtained_momo_cloaks (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  momo_cloak text not null references public.momo_cloaks(slug)
    on update cascade on delete cascade,
  created_at timestamptz not null default now(),
  constraint obtained_momo_cloaks_unique unique (user_id, momo_cloak)
);

create index if not exists obtained_momo_cloaks_user_id_idx
  on public.obtained_momo_cloaks (user_id);
create index if not exists obtained_momo_cloaks_momo_cloak_idx
  on public.obtained_momo_cloaks (momo_cloak);

-- RLS: public read (profiles show other users' progress), owner-only writes.
alter table public.obtained_momo_cloaks enable row level security;

create policy obtained_momo_cloaks_public_select on public.obtained_momo_cloaks
  for select using (true);
create policy obtained_momo_cloaks_owner_insert on public.obtained_momo_cloaks
  for insert with check ((select auth.uid()) = user_id);
create policy obtained_momo_cloaks_owner_update on public.obtained_momo_cloaks
  for update using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);
create policy obtained_momo_cloaks_owner_delete on public.obtained_momo_cloaks
  for delete using ((select auth.uid()) = user_id);

-- Toggle RPC. search_path is pinned to '' (every reference below is
-- schema-qualified) so the SECURITY DEFINER body can't be hijacked.
create or replace function public.toggle_obtained_momo_cloak(
  p_momo_cloak text
)
returns void
language plpgsql
security definer
set search_path to ''
as $$
begin
  delete from public.obtained_momo_cloaks
  where user_id    = (select auth.uid())
    and momo_cloak = p_momo_cloak;
  if not found then
    insert into public.obtained_momo_cloaks (user_id, momo_cloak)
    values ((select auth.uid()), p_momo_cloak);
  end if;
end;
$$;

commit;
