-- Display-only grouping label for season categories.
--
-- Some seasons list enough categories that they read better under a handful of
-- headings ("Exploration Rewards", "Styling Challenges"); others have few
-- enough that grouping is noise. season_categories.season_group is nullable and
-- that null IS the "ungrouped" state — a category with no group renders flat,
-- exactly as every category does today.
--
-- There is deliberately NO per-season "uses groups" boolean. Whether a season
-- groups is derivable: it does iff any category present in it has a non-null
-- season_group, which groupSeasonEntries already has in hand when it buckets
-- rows by season_category. A stored flag would be a second source of truth for
-- one fact and could contradict the data (a season flagged true whose
-- categories are all ungrouped renders a single "Other" bucket). Categories are
-- not scoped to one season either — season_category lives on outfit_sets and
-- variants — so a per-season boolean about a shared category set is asserting
-- something the category row already answers per-season for free.
--
-- This migration is written idempotently: the table and column were created by
-- hand in the dashboard before this file existed, so on the project where that
-- happened it repairs what is there (constraints, FK, RLS, trigger) without
-- disturbing the 7 rows already inserted, and on a fresh database it builds the
-- whole thing from nothing.

create table if not exists public.season_groups (
  id bigint primary key generated by default as identity,
  created_at timestamptz not null default now(),
  updated_at timestamptz default now(),
  slug text not null,
  title text not null,
  image_url text,
  description text
);

-- The dashboard-created table has only id/created_at/slug/title, so on that
-- project the create above is a no-op and these columns are genuinely missing.
-- image_url/description match the shape of seasons and season_categories;
-- updated_at is required by the trigger at the end of this file, which errors
-- on UPDATE ("record \"new\" has no field \"updated_at\"") without it.
alter table public.season_groups
  add column if not exists updated_at timestamptz default now(),
  add column if not exists image_url text,
  add column if not exists description text;

-- default now() only applies to new inserts, so the 7 pre-existing rows would
-- keep a null updated_at and stay invisible to the admin recents lists, which
-- filter nulls. Seed from created_at: a truthful lower bound, matching how
-- 20260804120000_add_timestamps_to_lookup_tables.sql backfilled its tables.
update public.season_groups
  set updated_at = coalesce(updated_at, created_at, now())
  where updated_at is null;

-- The dashboard-created table left slug/title nullable, while every peer lookup
-- table (seasons, season_categories, locations) has both NOT NULL. No existing
-- row violates this.
alter table public.season_groups
  alter column slug set not null,
  alter column title set not null;

-- UNIQUE on slug is what makes the FK below legal — Postgres requires the
-- referenced column to be unique — and matches seasons/season_categories, which
-- constrain both slug and title.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'season_groups_slug_key'
  ) then
    alter table public.season_groups add constraint season_groups_slug_key unique (slug);
  end if;

  if not exists (
    select 1 from pg_constraint where conname = 'season_groups_title_key'
  ) then
    alter table public.season_groups add constraint season_groups_title_key unique (title);
  end if;
end $$;

alter table public.season_categories
  add column if not exists season_group text;

-- Referencing slug rather than id, matching outfit_sets_season_category_fkey
-- and seasons_location_fkey. ON UPDATE CASCADE so renaming a group's slug
-- carries; ON DELETE SET NULL so deleting a group ungroups its categories
-- rather than blocking the delete or taking the categories with it.
do $$
begin
  if not exists (
    select 1 from pg_constraint where conname = 'season_categories_season_group_fkey'
  ) then
    alter table public.season_categories
      add constraint season_categories_season_group_fkey
      foreign key (season_group) references public.season_groups (slug)
      on update cascade on delete set null;
  end if;
end $$;

-- RLS was enabled on the dashboard-created table but carried no policies at
-- all, which makes the table invisible to everyone including admins — reads
-- return an empty array rather than erroring. Same public-read / admin-write
-- pair as seasons and season_categories.
alter table public.season_groups enable row level security;

drop policy if exists season_groups_read on public.season_groups;
create policy season_groups_read on public.season_groups
  for select using (true);

drop policy if exists season_groups_admin_write on public.season_groups;
create policy season_groups_admin_write on public.season_groups
  to authenticated
  using ((select is_admin()))
  with check ((select is_admin()));

-- Without this trigger updated_at would stay pinned at insert time; the admin
-- recents lists order by it. seasons and season_categories each got theirs in
-- 20260804120000_add_timestamps_to_lookup_tables.sql.
drop trigger if exists trg_season_groups_updated_at on public.season_groups;
create trigger trg_season_groups_updated_at
  before update on public.season_groups
  for each row execute function public.set_updated_at();
