


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE SCHEMA IF NOT EXISTS "public";


ALTER SCHEMA "public" OWNER TO "pg_database_owner";


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE OR REPLACE FUNCTION "public"."is_admin"() RETURNS boolean
    LANGUAGE "sql" STABLE SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
  select exists (
    select 1 from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
  );
$$;


ALTER FUNCTION "public"."is_admin"() OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."toggle_obtained"("p_eureka_set" "text", "p_category" "text", "p_color" "text") RETURNS "void"
    LANGUAGE "plpgsql" SECURITY DEFINER
    SET "search_path" TO ''
    AS $$
begin
  delete from public.obtained_eureka
  where user_id    = (select auth.uid())
    and eureka_set = p_eureka_set
    and category   = p_category
    and color      = p_color;

  if not found then
    insert into public.obtained_eureka (user_id, eureka_set, category, color)
    values ((select auth.uid()), p_eureka_set, p_category, p_color);
  end if;
end;
$$;


ALTER FUNCTION "public"."toggle_obtained"("p_eureka_set" "text", "p_category" "text", "p_color" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."eureka_sets" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" DEFAULT ''::"text" NOT NULL,
    "style" "text",
    "label" "text",
    "trial" "text",
    "rarity" bigint,
    "slug" "text" NOT NULL,
    "updated_at" timestamp with time zone,
    CONSTRAINT "Eureka_quality_check" CHECK (("rarity" <= 5)),
    CONSTRAINT "eureka_sets_rarity_check" CHECK ((("rarity" >= 2) AND ("rarity" <= 5)))
);


ALTER TABLE "public"."eureka_sets" OWNER TO "postgres";


ALTER TABLE "public"."eureka_sets" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Eureka_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."styles" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    "slug" "text" NOT NULL
);


ALTER TABLE "public"."styles" OWNER TO "postgres";


ALTER TABLE "public"."styles" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Styles_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."trials" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "image_url" "text",
    "slug" "text" NOT NULL,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."trials" OWNER TO "postgres";


ALTER TABLE "public"."trials" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."Trials_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."categories" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "image_url" "text",
    "slug" "text" NOT NULL
);


ALTER TABLE "public"."categories" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."colors" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" DEFAULT ''::"text",
    "image_url" "text",
    "id" bigint NOT NULL,
    "slug" "text" NOT NULL
);


ALTER TABLE "public"."colors" OWNER TO "postgres";


ALTER TABLE "public"."colors" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."colors_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."eureka_variants" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "image_url" "text",
    "eureka_set" "text",
    "category" "text",
    "color" "text",
    "default" boolean DEFAULT false NOT NULL,
    "slug" "text" NOT NULL,
    "updated_at" timestamp with time zone
);


ALTER TABLE "public"."eureka_variants" OWNER TO "postgres";


ALTER TABLE "public"."eureka_variants" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."images_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."labels" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text",
    "slug" "text" NOT NULL
);


ALTER TABLE "public"."labels" OWNER TO "postgres";


ALTER TABLE "public"."labels" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."labels_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."obtained_eureka" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "user_id" "uuid",
    "eureka_set" "text",
    "color" "text",
    "category" "text"
);

ALTER TABLE ONLY "public"."obtained_eureka" REPLICA IDENTITY FULL;

ALTER TABLE ONLY "public"."obtained_eureka" FORCE ROW LEVEL SECURITY;


ALTER TABLE "public"."obtained_eureka" OWNER TO "postgres";


ALTER TABLE "public"."obtained_eureka" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."obtained_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."profiles" (
    "id" "uuid" DEFAULT "gen_random_uuid"() NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "full_name" "text",
    "username" "text",
    "avatar_url" "text",
    "updated_at" timestamp with time zone,
    "role" "text" DEFAULT 'user'::"text" NOT NULL
);

ALTER TABLE ONLY "public"."profiles" FORCE ROW LEVEL SECURITY;


ALTER TABLE "public"."profiles" OWNER TO "postgres";


ALTER TABLE "public"."categories" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."types_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."colors"
    ADD CONSTRAINT "Colors_name_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."eureka_sets"
    ADD CONSTRAINT "Eureka_name_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."trials"
    ADD CONSTRAINT "Trials_name_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_pkey" PRIMARY KEY ("id", "title", "slug");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "categories_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."colors"
    ADD CONSTRAINT "colors_pkey" PRIMARY KEY ("slug");



ALTER TABLE ONLY "public"."colors"
    ADD CONSTRAINT "colors_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."eureka_sets"
    ADD CONSTRAINT "eureka_sets_pkey" PRIMARY KEY ("id", "slug");



ALTER TABLE ONLY "public"."eureka_sets"
    ADD CONSTRAINT "eureka_sets_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."eureka_variants"
    ADD CONSTRAINT "eureka_variants_pkey" PRIMARY KEY ("id", "slug");



ALTER TABLE ONLY "public"."eureka_variants"
    ADD CONSTRAINT "eureka_variants_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."labels"
    ADD CONSTRAINT "labels_pkey" PRIMARY KEY ("id", "slug");



ALTER TABLE ONLY "public"."labels"
    ADD CONSTRAINT "labels_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."labels"
    ADD CONSTRAINT "labels_title_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."obtained_eureka"
    ADD CONSTRAINT "obtained_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."styles"
    ADD CONSTRAINT "styles_pkey" PRIMARY KEY ("id", "slug");



ALTER TABLE ONLY "public"."styles"
    ADD CONSTRAINT "styles_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."styles"
    ADD CONSTRAINT "styles_title_key" UNIQUE ("title");



ALTER TABLE ONLY "public"."trials"
    ADD CONSTRAINT "trials_pkey" PRIMARY KEY ("id", "title", "slug");



ALTER TABLE ONLY "public"."trials"
    ADD CONSTRAINT "trials_slug_key" UNIQUE ("slug");



ALTER TABLE ONLY "public"."categories"
    ADD CONSTRAINT "types_name_key" UNIQUE ("title");



CREATE INDEX "categories_slug_idx" ON "public"."categories" USING "btree" ("slug");



CREATE INDEX "colors_slug_idx" ON "public"."colors" USING "btree" ("slug");



CREATE INDEX "eureka_sets_label_idx" ON "public"."eureka_sets" USING "btree" ("label");



CREATE INDEX "eureka_sets_slug_idx" ON "public"."eureka_sets" USING "btree" ("slug");



CREATE INDEX "eureka_sets_style_idx" ON "public"."eureka_sets" USING "btree" ("style");



CREATE INDEX "eureka_sets_trial_idx" ON "public"."eureka_sets" USING "btree" ("trial");



CREATE INDEX "eureka_variants_eureka_set_idx" ON "public"."eureka_variants" USING "btree" ("eureka_set");



CREATE INDEX "eureka_variants_slug_idx" ON "public"."eureka_variants" USING "btree" ("slug");



CREATE INDEX "labels_slug_idx" ON "public"."labels" USING "btree" ("slug");



CREATE UNIQUE INDEX "obtained_eureka_unique_item_idx" ON "public"."obtained_eureka" USING "btree" ("user_id", "eureka_set", "category", "color");



CREATE UNIQUE INDEX "obtained_unique_item_idx" ON "public"."obtained_eureka" USING "btree" ("user_id", "eureka_set", "category", "color");



CREATE INDEX "obtained_user_id_idx" ON "public"."obtained_eureka" USING "btree" ("user_id");



CREATE INDEX "styles_slug_idx" ON "public"."styles" USING "btree" ("slug");



CREATE INDEX "trials_slug_idx" ON "public"."trials" USING "btree" ("slug");



ALTER TABLE ONLY "public"."eureka_sets"
    ADD CONSTRAINT "eureka_sets_label_fkey" FOREIGN KEY ("label") REFERENCES "public"."labels"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."eureka_sets"
    ADD CONSTRAINT "eureka_sets_style_fkey" FOREIGN KEY ("style") REFERENCES "public"."styles"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."eureka_sets"
    ADD CONSTRAINT "eureka_sets_trial_fkey" FOREIGN KEY ("trial") REFERENCES "public"."trials"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."eureka_variants"
    ADD CONSTRAINT "eureka_variants_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."categories"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."eureka_variants"
    ADD CONSTRAINT "eureka_variants_color_fkey" FOREIGN KEY ("color") REFERENCES "public"."colors"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."eureka_variants"
    ADD CONSTRAINT "eureka_variants_eureka_set_fkey" FOREIGN KEY ("eureka_set") REFERENCES "public"."eureka_sets"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."obtained_eureka"
    ADD CONSTRAINT "obtained_eureka_category_fkey" FOREIGN KEY ("category") REFERENCES "public"."categories"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."obtained_eureka"
    ADD CONSTRAINT "obtained_eureka_color_fkey" FOREIGN KEY ("color") REFERENCES "public"."colors"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."obtained_eureka"
    ADD CONSTRAINT "obtained_eureka_eureka_set_fkey" FOREIGN KEY ("eureka_set") REFERENCES "public"."eureka_sets"("slug") ON UPDATE CASCADE;



ALTER TABLE ONLY "public"."obtained_eureka"
    ADD CONSTRAINT "obtained_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "auth"."users"("id");



ALTER TABLE ONLY "public"."profiles"
    ADD CONSTRAINT "profiles_id_fkey" FOREIGN KEY ("id") REFERENCES "auth"."users"("id");



CREATE POLICY "Enable delete for users based on user_id" ON "public"."obtained_eureka" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable delete for users based on user_id" ON "public"."profiles" FOR DELETE USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Enable insert for authenticated users only" ON "public"."profiles" FOR INSERT TO "authenticated" WITH CHECK (true);



CREATE POLICY "Enable insert for users based on user_id" ON "public"."obtained_eureka" FOR INSERT WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable read access for all users" ON "public"."categories" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."colors" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."eureka_sets" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."eureka_variants" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."labels" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."styles" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."trials" FOR SELECT USING (true);



CREATE POLICY "Enable update for users based on user_id" ON "public"."profiles" FOR UPDATE USING ((( SELECT "auth"."uid"() AS "uid") = "id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Enable users to view their own data only" ON "public"."obtained_eureka" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



CREATE POLICY "Enable users to view their own data only" ON "public"."profiles" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "Enable write for admin users only" ON "public"."eureka_sets" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = ( SELECT "auth"."uid"() AS "uid")) AND ("p"."role" = 'admin'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = ( SELECT "auth"."uid"() AS "uid")) AND ("p"."role" = 'admin'::"text")))));



CREATE POLICY "Enable write for admin users only" ON "public"."eureka_variants" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = ( SELECT "auth"."uid"() AS "uid")) AND ("p"."role" = 'admin'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = ( SELECT "auth"."uid"() AS "uid")) AND ("p"."role" = 'admin'::"text")))));



CREATE POLICY "Enable write for admin users only" ON "public"."trials" TO "authenticated" USING ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = ( SELECT "auth"."uid"() AS "uid")) AND ("p"."role" = 'admin'::"text"))))) WITH CHECK ((EXISTS ( SELECT 1
   FROM "public"."profiles" "p"
  WHERE (("p"."id" = ( SELECT "auth"."uid"() AS "uid")) AND ("p"."role" = 'admin'::"text")))));



ALTER TABLE "public"."categories" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "categories_admin_write" ON "public"."categories" TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "categories_read" ON "public"."categories" FOR SELECT USING (true);



ALTER TABLE "public"."colors" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "colors_admin_write" ON "public"."colors" TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "colors_read" ON "public"."colors" FOR SELECT USING (true);



ALTER TABLE "public"."eureka_sets" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "eureka_sets_admin_write" ON "public"."eureka_sets" TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "eureka_sets_read" ON "public"."eureka_sets" FOR SELECT USING (true);



ALTER TABLE "public"."eureka_variants" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "eureka_variants_admin_write" ON "public"."eureka_variants" TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "eureka_variants_read" ON "public"."eureka_variants" FOR SELECT USING (true);



ALTER TABLE "public"."labels" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "labels_admin_write" ON "public"."labels" TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "labels_read" ON "public"."labels" FOR SELECT USING (true);



ALTER TABLE "public"."obtained_eureka" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "obtained_user_policy" ON "public"."obtained_eureka" TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "user_id")) WITH CHECK ((( SELECT "auth"."uid"() AS "uid") = "user_id"));



ALTER TABLE "public"."profiles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "profiles_user_select" ON "public"."profiles" FOR SELECT TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "id"));



CREATE POLICY "profiles_user_update" ON "public"."profiles" FOR UPDATE TO "authenticated" USING ((( SELECT "auth"."uid"() AS "uid") = "id")) WITH CHECK (((( SELECT "auth"."uid"() AS "uid") = "id") AND ("role" = ( SELECT "profiles_1"."role"
   FROM "public"."profiles" "profiles_1"
  WHERE ("profiles_1"."id" = ( SELECT "auth"."uid"() AS "uid"))))));



ALTER TABLE "public"."styles" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "styles_admin_write" ON "public"."styles" TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "styles_read" ON "public"."styles" FOR SELECT USING (true);



ALTER TABLE "public"."trials" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "trials_admin_write" ON "public"."trials" TO "authenticated" USING (( SELECT "public"."is_admin"() AS "is_admin")) WITH CHECK (( SELECT "public"."is_admin"() AS "is_admin"));



CREATE POLICY "trials_read" ON "public"."trials" FOR SELECT USING (true);



GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";



GRANT ALL ON FUNCTION "public"."is_admin"() TO "anon";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "authenticated";
GRANT ALL ON FUNCTION "public"."is_admin"() TO "service_role";



GRANT ALL ON FUNCTION "public"."toggle_obtained"("p_eureka_set" "text", "p_category" "text", "p_color" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."toggle_obtained"("p_eureka_set" "text", "p_category" "text", "p_color" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."toggle_obtained"("p_eureka_set" "text", "p_category" "text", "p_color" "text") TO "service_role";



GRANT ALL ON TABLE "public"."eureka_sets" TO "anon";
GRANT ALL ON TABLE "public"."eureka_sets" TO "authenticated";
GRANT ALL ON TABLE "public"."eureka_sets" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Eureka_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Eureka_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Eureka_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."styles" TO "anon";
GRANT ALL ON TABLE "public"."styles" TO "authenticated";
GRANT ALL ON TABLE "public"."styles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Styles_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Styles_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Styles_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."trials" TO "anon";
GRANT ALL ON TABLE "public"."trials" TO "authenticated";
GRANT ALL ON TABLE "public"."trials" TO "service_role";



GRANT ALL ON SEQUENCE "public"."Trials_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."Trials_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."Trials_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."categories" TO "anon";
GRANT ALL ON TABLE "public"."categories" TO "authenticated";
GRANT ALL ON TABLE "public"."categories" TO "service_role";



GRANT ALL ON TABLE "public"."colors" TO "anon";
GRANT ALL ON TABLE "public"."colors" TO "authenticated";
GRANT ALL ON TABLE "public"."colors" TO "service_role";



GRANT ALL ON SEQUENCE "public"."colors_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."colors_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."colors_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."eureka_variants" TO "anon";
GRANT ALL ON TABLE "public"."eureka_variants" TO "authenticated";
GRANT ALL ON TABLE "public"."eureka_variants" TO "service_role";



GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."images_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."labels" TO "anon";
GRANT ALL ON TABLE "public"."labels" TO "authenticated";
GRANT ALL ON TABLE "public"."labels" TO "service_role";



GRANT ALL ON SEQUENCE "public"."labels_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."labels_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."labels_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."obtained_eureka" TO "anon";
GRANT ALL ON TABLE "public"."obtained_eureka" TO "authenticated";
GRANT ALL ON TABLE "public"."obtained_eureka" TO "service_role";



GRANT ALL ON SEQUENCE "public"."obtained_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."obtained_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."obtained_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."profiles" TO "anon";
GRANT ALL ON TABLE "public"."profiles" TO "authenticated";
GRANT ALL ON TABLE "public"."profiles" TO "service_role";



GRANT ALL ON SEQUENCE "public"."types_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."types_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."types_id_seq" TO "service_role";



ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";







