-- Create the locations and seasons lookup tables.
--
-- These tables exist on the live database but were originally created outside
-- the migration history (via the dashboard), so a clean rebuild never had them.
-- Later migrations (20260617000001 onward) ALTER seasons and FK-reference both
-- tables, which fails on a fresh database. This migration backfills the base
-- schema so the committed sequence is self-contained.
--
-- Base columns only: image_url/description are added to seasons later by
-- 20260617000001_add_season_image_description_and_categories.sql.

CREATE TABLE IF NOT EXISTS public.locations (
  id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  slug        text        NOT NULL,
  title       text        NOT NULL,
  CONSTRAINT locations_pkey PRIMARY KEY (id, slug),
  CONSTRAINT locations_slug_key UNIQUE (slug),
  CONSTRAINT locations_title_key UNIQUE (title)
);

CREATE TABLE IF NOT EXISTS public.seasons (
  id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  timestamptz NOT NULL DEFAULT now(),
  slug        text        NOT NULL,
  title       text        NOT NULL,
  location    text,
  CONSTRAINT seasons_pkey PRIMARY KEY (id, slug),
  CONSTRAINT seasons_slug_key UNIQUE (slug),
  CONSTRAINT seasons_title_key UNIQUE (title),
  CONSTRAINT seasons_location_fkey
    FOREIGN KEY (location) REFERENCES public.locations(slug)
    ON UPDATE CASCADE
);

-- RLS: public read, admin write
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;

CREATE POLICY locations_read ON public.locations
  FOR SELECT USING (true);

CREATE POLICY locations_admin_write ON public.locations
  FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

ALTER TABLE public.seasons ENABLE ROW LEVEL SECURITY;

CREATE POLICY seasons_read ON public.seasons
  FOR SELECT USING (true);

CREATE POLICY seasons_admin_write ON public.seasons
  FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));
