-- Add image_url and description to seasons
ALTER TABLE public.seasons ADD COLUMN IF NOT EXISTS image_url text;
ALTER TABLE public.seasons ADD COLUMN IF NOT EXISTS description text;

-- Category / sub-section lookup
CREATE TABLE IF NOT EXISTS public.season_categories (
  id          bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  slug        text         NOT NULL,
  title       text         NOT NULL,
  image_url   text,
  description text,
  CONSTRAINT season_categories_pkey PRIMARY KEY (id),
  CONSTRAINT season_categories_slug_key UNIQUE (slug),
  CONSTRAINT season_categories_title_key UNIQUE (title)
);

-- Many-to-many join between seasons and categories
CREATE TABLE IF NOT EXISTS public.season_category_map (
  season    text NOT NULL,
  category  text NOT NULL,
  CONSTRAINT season_category_map_pkey PRIMARY KEY (season, category),
  CONSTRAINT season_category_map_season_fkey
    FOREIGN KEY (season) REFERENCES public.seasons(slug)
    ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT season_category_map_category_fkey
    FOREIGN KEY (category) REFERENCES public.season_categories(slug)
    ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX IF NOT EXISTS season_category_map_category_idx
  ON public.season_category_map (category);

-- RLS: public read, admin write
ALTER TABLE public.season_categories ENABLE ROW LEVEL SECURITY;

CREATE POLICY season_categories_read ON public.season_categories
  FOR SELECT USING (true);

CREATE POLICY season_categories_admin_write ON public.season_categories
  FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));

ALTER TABLE public.season_category_map ENABLE ROW LEVEL SECURITY;

CREATE POLICY season_category_map_read ON public.season_category_map
  FOR SELECT USING (true);

CREATE POLICY season_category_map_admin_write ON public.season_category_map
  FOR ALL TO authenticated
  USING ((SELECT public.is_admin()))
  WITH CHECK ((SELECT public.is_admin()));
